    This is my script for Numerical Method (WID3004) Assignment 
    Name : Muhammad Afiq Irfan Bin Manor
    Matrix Number: 17167014/2 

# Bisection method
question 1 & 2

In [1]:
import math
import numpy as np

In [22]:
def bisection(fx,a,b,iteration,stoppingcondition):

    # proceed to this condition when has stopping condition such as interval width 
    if(stoppingcondition is not None):
        while(True):
            c = (a+b)/2
            fc = fx(c)
            fa = fx(a)
            fb = fx(b)
            print(a, b, fa, fb, c, fc,b-a)

            if(abs(b-a)<= stoppingcondition):
                break

            if(fc == 0):
                return c
            elif(fc * fa < 0):
                b = c
            elif(fb * fc < 0):
                a = c
            
        return a if abs(fa) < abs(fb) else b

    else: #continue this condition when the process only based on number of iteration

        for i in range(iteration):
            c = (a+b)/2
            fc = fx(c)
            fa = fx(a)
            fb = fx(b)
            print(a, b, fa, fb, c, fc)

            if(fc == 0):
                return c
            elif(fc * fa < 0):
                b = c
            elif(fb * fc < 0):
                a = c

        return a if abs(fa) < abs(fb) else b

In [23]:
''' These are the functions used '''
def fx_example(x):
    return x**2 - 3
    
def fx_q2(x):
    return x**6-x-1

In [24]:
# test for question 1
print(f"The root is = {bisection(fx_example,1,2,7,None)}")

1 2 -2 1 1.5 -0.75
1.5 2 -0.75 1 1.75 0.0625
1.5 1.75 -0.75 0.0625 1.625 -0.359375
1.625 1.75 -0.359375 0.0625 1.6875 -0.15234375
1.6875 1.75 -0.15234375 0.0625 1.71875 -0.0458984375
1.71875 1.75 -0.0458984375 0.0625 1.734375 0.008056640625
1.71875 1.734375 -0.0458984375 0.008056640625 1.7265625 -0.01898193359375
The root is = 1.734375


In [25]:
# question 2
print(f"The root is = {bisection(fx_q2,1,2,None,stoppingcondition=0.01)}")

1 2 -1 61 1.5 8.890625 1
1 1.5 -1 8.890625 1.25 1.564697265625 0.5
1 1.25 -1 1.564697265625 1.125 -0.09771347045898438 0.25
1.125 1.25 -0.09771347045898438 1.564697265625 1.1875 0.6166530251502991 0.125
1.125 1.1875 -0.09771347045898438 0.6166530251502991 1.15625 0.23326892498880625 0.0625
1.125 1.15625 -0.09771347045898438 0.23326892498880625 1.140625 0.06157783210801426 0.03125
1.125 1.140625 -0.09771347045898438 0.06157783210801426 1.1328125 -0.01957555101375874 0.015625
1.1328125 1.140625 -0.01957555101375874 0.06157783210801426 1.13671875 0.02061899522150057 0.0078125
The root is = 1.1328125


# Secant method
question 3, 4 & 5

In [26]:
def secant(fx,a,b,iteration):
    x_curr = b
    x_prev = a
    for i in range(1,iteration):
        x_new = x_curr - (((x_curr - x_prev)/(fx(x_curr)-fx(x_prev)))*fx(x_curr))
        print(i,x_prev,x_curr,fx(x_prev),fx(x_curr))

        x_prev = x_curr
        x_curr = x_new

    return x_curr

In [27]:
''' These are the functions used '''

def fx_example(x):
    return x**2-2

def fx_q4(x):
    return x**4-5

def fx_q5(x):
    return math.exp(x)-(2-x)**3

In [28]:
# test for question 3
print(f"The root is = {secant(fx_example,1,1.5,4)}")

1 1 1.5 -1 0.25
2 1.5 1.4 0.25 -0.04000000000000026
3 1.4 1.4137931034482758 -0.04000000000000026 -0.0011890606420930094
The root is = 1.4142156862745099


In [29]:
# question 4
print(f"The root is = {secant(fx_q4,1,2,10)}")

1 1 2 -4 11
2 2 1.2666666666666666 11 -2.4257580246913584
3 1.2666666666666666 1.399164899901277 -2.4257580246913584 -1.1675578606125185
4 1.399164899901277 1.522117795749609 -1.1675578606125185 0.3677595596736172
5 1.522117795749609 1.4926664899542565 0.3677595596736172 -0.035778714129013345
6 1.4926664899542565 1.4952777164950466 -0.035778714129013345 -0.0009504091797589709
7 1.4952777164950466 1.495348972724094 -0.0009504091797589709 2.561314293103578e-06
8 1.495348972724094 1.4953487812075685 2.561314293103578e-06 -1.8259260770037145e-10
9 1.4953487812075685 1.4953487812212205 -1.8259260770037145e-10 -8.881784197001252e-16
The root is = 1.4953487812212205


In [30]:
# question 5
print(f"The root is = {secant(fx_q5,0,5,10)}")

1 0 5 -7.0 175.4131591025766
2 5 0.19187212245098184 175.4131591025766 -4.699844662232567
3 0.19187212245098184 0.3173347690577644 -4.699844662232567 -3.390772576136788
4 0.3173347690577644 0.6423094637001294 -3.390772576136788 -0.6017972021770679
5 0.6423094637001294 0.7124315823248121 -0.6017972021770679 -0.09562958511859243
6 0.7124315823248121 0.7256796623791717 -0.09562958511859243 -0.003224116126523402
7 0.7256796623791717 0.7261419006970401 -0.003224116126523402 -1.7789607834828303e-05
8 0.7261419006970401 0.7261444653261735 -1.7789607834828303e-05 -3.3242000263555838e-09
9 0.7261444653261735 0.7261444658054945 -3.3242000263555838e-09 -3.552713678800501e-15
The root is = 0.7261444658054951


# Lagrange method
question 6

In [31]:
def x_value(n,i):
    return (10*i)/n - 5

def y_value(i): # the value return will be use as input for f(x)
    return (i/10) - 5

def y_function_a(x):
    return 1/(1+x**2)

def y_function_b(x):
    return math.sin(x)

def y_function_c(x):
    return (math.tan(x)+1)/(math.sin(x**2) + 2)

In [32]:
def lagrange(n,x,func):
    # print(f'Calculating for p{n}...')
    pn = 0
    for i in range(n+1):
        xi = x_value(n,i) #this is for multiplication the y[i] value after got L[i] polynomial, using f(x) function
        temp = 1

        for j in range(n+1): # lagrange iteration multiplication
            if(j != i ): 
                temp = temp * ( (x - x_value(n,j)) / (x_value(n,i) - (x_value(n,j))) ) 

        # print(f'this is function(x{i}) : {func(xi)}')
        pn = pn + (temp * func(xi))
        # print(f'this is pn : {pn}')
    return pn

In [33]:
n = [2,4,6,8,10,12,14,16] # n values
max_err = 0
list_err = []

In [34]:
''' Using function (a) '''
for i in range(len(n)):
    max_err = 0
    print(f'calculating p{n[i]}...')

    for j in range(101):
        # print(f'this is for i = {j}')
        x = y_value(j)
        ans = lagrange(n[i],x,y_function_a)
        error = abs(y_function_a(x) - ans)
        print(f'f({x}) = {y_function_a(x)}   p({x}) = {ans}      error = {error}\n')
        list_err.append(error)
        
        if(error > max_err):
            max_err = error
    print(f'The max error for p{n[i]} is : {max_err}')

calculating p2...
f(-5.0) = 0.038461538461538464   p(-5.0) = 0.038461538461538464      error = 0.0

f(-4.9) = 0.03998400639744101   p(-4.9) = 0.07653846153846139      error = 0.036554455141020376

f(-4.8) = 0.0415973377703827   p(-4.8) = 0.11384615384615394      error = 0.07224881607577124

f(-4.7) = 0.04330879168471199   p(-4.7) = 0.1503846153846153      error = 0.10707582369990332

f(-4.6) = 0.04512635379061373   p(-4.6) = 0.18615384615384625      error = 0.14102749236323253

f(-4.5) = 0.047058823529411764   p(-4.5) = 0.22115384615384617      error = 0.1740950226244344

f(-4.4) = 0.04911591355599213   p(-4.4) = 0.25538461538461527      error = 0.20626870182862314

f(-4.3) = 0.051308363263211906   p(-4.3) = 0.2888461538461539      error = 0.237537790582942

f(-4.2) = 0.0536480686695279   p(-4.2) = 0.32153846153846144      error = 0.26789039286893357

f(-4.1) = 0.05614823133071309   p(-4.1) = 0.3534615384615386      error = 0.2973133071308255

f(-4.0) = 0.058823529411764705   p(-4.0) =

In [35]:
''' Using function (b) '''
for i in range(len(n)):
    max_err = 0
    print(f'calculating p{n[i]}...')

    for j in range(101):
        # print(f'this is for i = {j}')
        x = y_value(j)
        ans = lagrange(n[i],x,y_function_b)
        error = abs(y_function_b(x) - ans)
        print(f'f({x}) = {y_function_b(x)}   p({x}) = {ans}      error = {error}\n')
        list_err.append(error)
        # print(f'Value for p{n[7]} with value x of {x} is = {ans} and the error with f({x}) is : {y_function_a(x)} - {ans} = {error}')
        if(error > max_err):
            max_err = error
    print(f'The max error for p{n[i]} is : {max_err}')

calculating p2...
f(-5.0) = 0.9589242746631385   p(-5.0) = 0.9589242746631385      error = 0.0

f(-4.9) = 0.9824526126243325   p(-4.9) = 0.9397457891698757      error = 0.042706823454456755

f(-4.8) = 0.9961646088358407   p(-4.8) = 0.920567303676613      error = 0.07559730515922769

f(-4.7) = 0.9999232575641008   p(-4.7) = 0.9013888181833501      error = 0.09853443938075068

f(-4.6) = 0.9936910036334644   p(-4.6) = 0.8822103326900873      error = 0.1114806709433771

f(-4.5) = 0.977530117665097   p(-4.5) = 0.8630318471968246      error = 0.11449827046827243

f(-4.4) = 0.9516020738895161   p(-4.4) = 0.843853361703562      error = 0.10774871218595417

f(-4.3) = 0.9161659367494549   p(-4.3) = 0.8246748762102991      error = 0.09149106053915579

f(-4.2) = 0.8715757724135882   p(-4.2) = 0.8054963907170364      error = 0.06607938169655181

f(-4.1) = 0.8182771110644103   p(-4.1) = 0.7863179052237734      error = 0.03195920584063683

f(-4.0) = 0.7568024953079282   p(-4.0) = 0.7671394197305108  

In [36]:
''' Using function (c) '''
for i in range(len(n)):
    max_err = 0
    print(f'calculating p{n[i]}...')

    for j in range(101):
        # print(f'this is for i = {j}')
        x = y_value(j)
        ans = lagrange(n[i],x,y_function_c)
        error = abs(y_function_c(x) - ans)
        print(f'f({x}) = {y_function_c(x)}   p({x}) = {ans}      error = {error}\n')
        list_err.append(error)
        # print(f'Value for p{n[7]} with value x of {x} is = {ans} and the error with f({x}) is : {y_function_a(x)} - {ans} = {error}')
        if(error > max_err):
            max_err = error
    print(f'The max error for p{n[i]} is : {max_err}')

calculating p2...
f(-5.0) = 2.345471105962223   p(-5.0) = 2.345471105962223      error = 0.0

f(-4.9) = 5.704417769163938   p(-4.9) = 2.307867202346783      error = 3.396550566817155

f(-4.8) = 10.929606218920151   p(-4.8) = 2.2702916449148622      error = 8.65931457400529

f(-4.7) = -41.925190798675615   p(-4.7) = 2.2327444336664586      error = 44.157935232342076

f(-4.6) = -2.870032347538308   p(-4.6) = 2.1952255686015736      error = 5.065257916139881

f(-4.5) = -1.2183223783518486   p(-4.5) = 2.157735049720207      error = 3.3760574280720554

f(-4.4) = -0.8423826494220202   p(-4.4) = 2.1202728770223587      error = 2.962655526444379

f(-4.3) = -0.7801805519670314   p(-4.3) = 2.082839050508028      error = 2.863019602475059

f(-4.2) = -0.7306246330773771   p(-4.2) = 2.0454335701772153      error = 2.7760582032545926

f(-4.1) = -0.3822887525830379   p(-4.1) = 2.008056436029921      error = 2.390345188612959

f(-4.0) = -0.09218012270321266   p(-4.0) = 1.9707076480661454      error = 

# Jacobi method
question 7

In [2]:
def make_diagonal_dominant(matrix, b):
    max_col_index = np.argmax(np.abs(matrix), axis=0)
    matrix = matrix[max_col_index]
    b = b[max_col_index]

    return matrix, b

def jacobi(matrix,iteration,b, x=None):
    
    if x is None:
        x = np.zeros(len(matrix[0]))
    
    D = np.diag(matrix)
    R = matrix - np.diagflat(D)

    for i in range(iteration):
        x = (b - np.dot(R,x)) / D
        print(f'Iteration {i+1}:\n x = {x}')
    return x

In [3]:
A = np.array([ [3,12,0,-1,0,0], [4,0,31,1,0,0] , [2,1,0,0,17,-3], [27,2,0,0,0,1], [0,0,0,-1,1,11], [0,0,0,24,-1,0] ])
b = np.array([39,117,12,98,14,55])


A, b = make_diagonal_dominant(A,b)
print(A)
print(b)

jacobi(A,10,b)

[[27  2  0  0  0  1]
 [ 3 12  0 -1  0  0]
 [ 4  0 31  1  0  0]
 [ 0  0  0 24 -1  0]
 [ 2  1  0  0 17 -3]
 [ 0  0  0 -1  1 11]]
[ 98  39 117  55  12  14]
Iteration 1:
 x = [3.62962963 3.25       3.77419355 2.29166667 0.70588235 1.27272727]
Iteration 2:
 x = [3.34175084 2.53356481 3.23192951 2.32107843 0.31228956 1.41688948]
Iteration 3:
 x = [3.38948077 2.60798549 3.26812639 2.30467873 0.41374129 1.45534444]
Iteration 4:
 x = [3.38254387 2.59468637 3.26249672 2.30890589 0.41053449 1.44463068]
Iteration 5:
 x = [3.3839258  2.59677286 3.26325544 2.30877227 0.41024223 1.44530649]
Iteration 6:
 x = [3.38374621 2.59641624 3.26308144 2.30876009 0.41007618 1.44532091]
Iteration 7:
 x = [3.3837721  2.59646012 3.263105   2.30875317 0.41012083 1.4453349 ]
Iteration 8:
 x = [3.38376833 2.59645307 3.26310189 2.30875503 0.41011767 1.44533021]
Iteration 9:
 x = [3.38376902 2.59645417 3.26310231 2.3087549  0.4101177  1.44533067]
Iteration 10:
 x = [3.38376893 2.59645399 3.26310223 2.3087549  0.4101176

array([3.38376893, 2.59645399, 3.26310223, 2.3087549 , 0.41011763,
       1.44533065])

# Gauss-Seidel method
question 8

In [4]:
def GaussSeidel(matrix,b,iteration,x=None):

    if x is None:
        x = np.zeros(len(matrix[0]))

    for iterations in range(iteration):
        for i in range(len(matrix[0])):
            d = b[i]

            for j in range(len(matrix[0])):
                if( i != j ):
                    d = d - (matrix[i][j]*x[j])
            x[i] = d/matrix[i][i]
        print(f'Iteration {iterations+1}:\n x = {x}')
    return x

In [5]:
A = np.array([[5,-2,-1,1],[-2,4,1,0],[1,2,6,-1],[-1,0,1,6]])
b = np.array([6,0,6,-14])

A,b = make_diagonal_dominant(A,b)
print(A)
print(b)

GaussSeidel(A,b,10)

[[ 5 -2 -1  1]
 [-2  4  1  0]
 [ 1  2  6 -1]
 [-1  0  1  6]]
[  6   0   6 -14]
Iteration 1:
 x = [ 1.2         0.6         0.6        -2.23333333]
Iteration 2:
 x = [ 2.00666667  0.85333333  0.00888889 -2.00037037]
Iteration 3:
 x = [ 1.94318519  0.96937037  0.01961728 -2.01273868]
Iteration 4:
 x = [ 1.99421934e+00  9.92205350e-01  1.43854595e-03 -2.00120320e+00]
Iteration 5:
 x = [ 1.99741049e+00  9.98345608e-01  7.82515623e-04 -2.00056200e+00]
Iteration 6:
 x = [ 1.99960715e+00  9.99607945e-01  1.02493150e-04 -2.00008256e+00]
Iteration 7:
 x = [ 1.99988019e+00  9.99914471e-01  3.47188047e-05 -2.00002576e+00]
Iteration 8:
 x = [ 1.99997788e+00  9.99980262e-01  5.97301908e-06 -2.00000468e+00]
Iteration 9:
 x = [ 1.99999424e+00  9.99995625e-01  1.63891859e-06 -2.00000123e+00]
Iteration 10:
 x = [ 1.99999882e+00  9.99999002e-01  3.22800478e-07 -2.00000025e+00]


array([ 1.99999882e+00,  9.99999002e-01,  3.22800478e-07, -2.00000025e+00])